version: '1'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../bedrock:/var/www/html
      - ./nginx/ssl:/etc/ssl:ro
      - ./nginx/logs:/var/log/nginx
  wordpress:
    build: ./php8 
    env_file:
      - ../bedrock/.env
    volumes:
      - ../bedrock:/var/www/html
    ports:
      - 9000:9000
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wp'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - 3306:3306